# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jan Carlo Viray
tagline:             'Senior Front-End Developer / Full-Stack Agile'
description:         'Lessons learned. Inspirations and thoughts. Made by <a href="https://twitter.com/jancarloviray" target="_blank">jancarloviray</a>.'
url:                 http://www.jancarloviray.com
shorturl:            www.jancarloviray.com
baseurl:             http://jancarloviray.github.io/
paginate:            10

# About/contact
author:
  name:              Jan Carlo Viray
  url:               https://twitter.com/jancarloviray
  email:             virayjancarlo@yahoo.com

github:
  repo:              https://github.com/jancarloviray/jancarloviray.github.io
  
pages_list:
  About: '/about/'
  Archive: '/archive/'
  #Feed: '/atom.xml'

# Custom vars
version:             1.0.0
